-- 006_seed_sop_content.sql
-- Seeds the SOP step content for the 4 SOPs (base seed had sops metadata but no
-- sop_steps). Idempotent upserts keyed by (sop_key, step_number).
-- GENERATED from frontend/lib/mock/sops.ts by scripts/gen-sop-content.ts
-- — edit the source SOPs, not this file.
begin;
insert into sops (key, name, icon, total_steps) values ('projects', 'Zoho Projects', '📁', 7)
  on conflict (key) do update set name=excluded.name, icon=excluded.icon, total_steps=excluded.total_steps;
insert into sops (key, name, icon, total_steps) values ('desk', 'Zoho Desk', '🎫', 8)
  on conflict (key) do update set name=excluded.name, icon=excluded.icon, total_steps=excluded.total_steps;
insert into sops (key, name, icon, total_steps) values ('timekeeping', 'Timekeeping', '⏱️', 6)
  on conflict (key) do update set name=excluded.name, icon=excluded.icon, total_steps=excluded.total_steps;
insert into sops (key, name, icon, total_steps) values ('client_access', 'Client Access', '🔑', 5)
  on conflict (key) do update set name=excluded.name, icon=excluded.icon, total_steps=excluded.total_steps;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('projects', 1, '🔐', 'Log In to Zoho Projects', 'Access your Zoho Projects account using your Jera company email credentials.', 'Go to projects.zoho.com/portal/jeradotcodotza and sign in with your @jera.co.za email.', 'Open projects.zoho.com', 'Bookmark this URL — you''ll use it every day.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('projects', 2, '🗂️', 'Understand the Dashboard', 'The dashboard shows your assigned tasks, deadlines and project activity.', 'On the left sidebar: My Work, Projects, Timesheets and Reports. Start your day on ''My Work''.', 'Click ''My Work'' in the sidebar', 'Use the ''Due Today'' filter to focus.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('projects', 3, '📁', 'Select Your Project', 'Navigate to the project(s) you''ve been assigned to.', 'Click ''Projects'' → select your project. Inside: Tasks, Milestones, Files, Feed, Timesheets.', 'Click ''Projects'' → select your project', 'Ask your manager which projects are priority.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('projects', 4, '✅', 'Update Task Statuses', 'Keep your task statuses accurate — critical for project visibility.', 'Open a task → change status: Open → In Progress → Completed. Add comments.', 'Open a task → change status → add comment', 'Status updates replace status meetings.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('projects', 5, '⏱️', 'Log Time Daily', 'Time logging feeds directly into billing and payroll — non-negotiable.', 'Timesheets → Log Time. Select project/task, enter hours, add a note. Sync Memtime daily.', 'Timesheets → Log Time → enter hours', 'Log at end of each day. Never wait until Friday.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('projects', 6, '💬', 'Use the Project Feed', 'The Feed is your team communication channel inside each project.', 'Use @mentions. Post updates, flag blockers. Avoid email for project updates.', 'Open project → ''Feed'' → post update', 'Tag your manager on client-facing updates.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('projects', 7, '📤', 'Upload Files to SharePoint', 'All deliverables must be stored in SharePoint — not locally.', 'Upload to SharePoint first, then attach link to Zoho task.', 'Upload to SharePoint → paste link', 'Never store docs on local drive only.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('desk', 1, '🔐', 'Log In to Zoho Desk', 'Access Zoho Desk using your Jera credentials.', 'Go to desk.zoho.com and sign in. Same Zoho One credentials.', 'Open desk.zoho.com', 'Same login as Zoho Projects.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('desk', 2, '🎫', 'Understand the Ticket Dashboard', 'Dashboard shows open, pending and resolved tickets.', 'Left panel: My Tickets, All Tickets, Views, Reports. Start on ''My Tickets''.', 'Click ''My Tickets''', 'Red = urgent, address within 1 hour.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('desk', 3, '➕', 'Create a New Ticket', 'Always log client issues as tickets — never via email.', 'Click ''+ New Ticket''. Fill: Contact, Subject, Description, Department, Priority, Due Date.', '''+ New Ticket'' → fill fields → Submit', 'Good subject: ''Client — Issue Summary''.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('desk', 4, '🔄', 'Update Ticket Status', 'Keep statuses accurate for team visibility.', 'Statuses: Open → In Progress → On Hold → Resolved → Closed.', 'Open ticket → change status → comment', 'Waiting on client? Set ''On Hold''.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('desk', 5, '↩️', 'Reply to a Ticket', 'All client communication inside Zoho Desk.', 'Click ''Reply''. Use ''Internal Note'' for colleagues.', 'Open ticket → Reply → Send', 'Read full thread before replying.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('desk', 6, '🚨', 'Escalate Overdue Tickets', 'Escalate before SLA breach — don''t wait.', 'Three-dot menu → Escalate → Select your manager → Add note.', 'Escalate → Select manager → Add note', 'SLA breach = client trust breach.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('desk', 7, '📝', 'Use Internal Notes', 'Internal notes visible only to your team.', 'Click ''Internal Note'' (not Reply) for internal discussions.', '''Internal Note'' → type → Save', 'Never put opinions in Reply field.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('desk', 8, '✅', 'Close & Archive Tickets', 'Resolve properly — never delete tickets.', 'Set ''Resolved'', send closing message. Auto-closes after 7 days.', '''Resolved'' → closing message', 'Confirm resolution before closing.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('timekeeping', 1, '📥', 'Install Memtime', 'Download and install Memtime on your work laptop.', 'Memtime auto-tracks which apps, documents, and websites you use. Records locally on your machine.', 'Download from memtime.com → install → sign in', 'Memtime runs silently — no need to start/stop.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('timekeeping', 2, '📊', 'Review Your Timeline', 'At end of each day, open Memtime and review what it captured.', 'Memtime shows a visual timeline colour-coded by application.', 'Open Memtime → review today''s timeline', 'Do this daily while it''s fresh.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('timekeeping', 3, '✍️', 'Create Time Entries', 'Drag on timeline to create entries and assign to Zoho Projects.', 'Select time block, assign to project and task, add description. Memtime syncs to Zoho.', 'Select block → assign project/task → sync', 'Be specific — ''Development work'' is too vague.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('timekeeping', 4, '🔄', 'Sync to Zoho Daily', 'Sync Memtime entries to Zoho Projects end of every day.', 'Click ''Sync'' in Memtime. Verify entries in Zoho Timesheets.', 'Memtime → Sync → verify in Zoho', 'Never leave sync until Friday.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('timekeeping', 5, '💵', 'Billable vs Non-Billable', 'Mark time correctly — billable time gets invoiced to clients.', 'Billable: client work, client meetings, travel. Non-billable: internal meetings, training, admin.', 'Tag each entry as billable or non-billable', 'When in doubt, ask your manager.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('timekeeping', 6, '📋', 'Timesheet Accompanies Expenses', 'A timesheet copy must be attached to any expense claim.', 'Per Jera policy, no expense claim processed without timesheet. Submit by the 25th.', 'Export timesheet → attach to expense claim', 'No timesheet = no reimbursement.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('client_access', 1, '👤', 'Meet Your Project Manager', 'Schedule a handover session with your assigned Project Manager.', 'Your PM will walk you through your client assignments, project scope, and key contacts. This is your first real client-facing step.', 'Message your PM to schedule a 30-min handover', 'Bring a notebook — there will be a lot of names and URLs.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('client_access', 2, '🔐', 'Collect Client Login Credentials', 'Get all client system URLs, usernames, and access details from your PM.', 'Your PM will share client VPN details, Sage login URLs, remote desktop credentials, and any client-specific portals. Store these securely in your password manager.', 'Request credentials list from PM → store in password manager', 'Never store passwords in plain text or on sticky notes.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('client_access', 3, '🌐', 'Test All Client Connections', 'Log into every client system to verify access before your first task.', 'Test each URL, VPN connection, and login. If anything fails, report it immediately to your PM and IT (Siko). Don''t wait until you need it urgently.', 'Test each login → report any failures to PM + IT', 'Do this on day 1 of each new project assignment.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('client_access', 4, '📋', 'Review Client Project Documentation', 'Read the project charter, scope document, and any existing deliverables.', 'Your PM will point you to the SharePoint folder for each project. Read the charter, BRD/FDD, and any progress reports. Understand where the project is before you start contributing.', 'Open SharePoint → Projects folder → read key docs', 'Ask questions early — it''s better than assumptions later.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
insert into sop_steps (sop_key, step_number, icon, title, description, detail, action_text, tip_text) values ('client_access', 5, '✅', 'Confirm Ready Status', 'Let your PM know you have access, have read the docs, and are ready to start.', 'Send a message to your PM confirming: all logins work, documentation reviewed, and you understand your first deliverable. This closes the client access SOP.', 'Message PM: ''All access confirmed, ready to start''', 'Being proactive builds trust fast.')
  on conflict (sop_key, step_number) do update set icon=excluded.icon, title=excluded.title, description=excluded.description, detail=excluded.detail, action_text=excluded.action_text, tip_text=excluded.tip_text;
commit;
