-- 007_seed_onboarding_template.sql
-- Seeds the full onboarding task template (phases + tasks). The base seed (003)
-- shipped only a 5-task subset; this loads the complete template so a real
-- onboarding workflow generates the proper task list. Idempotent upserts.
-- GENERATED from frontend/lib/mock/onboarding.ts by scripts/gen-onboarding-template.ts
begin;
insert into onboarding_phases (id, name, icon, days_label, visibility, sort_order) values ('pre', 'Pre-Arrival', '📋', 'Before Day 1', 'admin', 1)
  on conflict (id) do update set name=excluded.name, icon=excluded.icon, days_label=excluded.days_label, visibility=excluded.visibility, sort_order=excluded.sort_order;
insert into onboarding_phases (id, name, icon, days_label, visibility, sort_order) values ('day1', 'Day 1 — Welcome', '🎉', 'Day 1', 'both', 2)
  on conflict (id) do update set name=excluded.name, icon=excluded.icon, days_label=excluded.days_label, visibility=excluded.visibility, sort_order=excluded.sort_order;
insert into onboarding_phases (id, name, icon, days_label, visibility, sort_order) values ('it', 'IT Setup', '💻', 'Day 1–2', 'both', 3)
  on conflict (id) do update set name=excluded.name, icon=excluded.icon, days_label=excluded.days_label, visibility=excluded.visibility, sort_order=excluded.sort_order;
insert into onboarding_phases (id, name, icon, days_label, visibility, sort_order) values ('hr', 'HR Admin', '📑', 'Day 2–3', 'admin', 4)
  on conflict (id) do update set name=excluded.name, icon=excluded.icon, days_label=excluded.days_label, visibility=excluded.visibility, sort_order=excluded.sort_order;
insert into onboarding_phases (id, name, icon, days_label, visibility, sort_order) values ('training', 'Orientation', '🎓', 'Week 1–2', 'employee', 5)
  on conflict (id) do update set name=excluded.name, icon=excluded.icon, days_label=excluded.days_label, visibility=excluded.visibility, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t1', 'pre', 'Send welcome letter & arrival info', 'hr', 'high', null, -3, 'admin', false, 1)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t2', 'pre', 'Notify IT to prepare equipment', 'hr', 'high', 'zoho', -3, 'admin', false, 2)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t3', 'pre', 'Collect clothing size from new employee', 'joann', 'medium', null, -2, 'admin', false, 3)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t4', 'pre', 'Prepare laptop / workstation', 'siko', 'high', null, -1, 'admin', false, 4)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t6', 'day1', 'Welcome & office tour', 'ryan', 'high', null, 0, 'both', false, 1)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t7', 'day1', 'Sign employment contract & NDA', 'hr', 'high', null, 0, 'both', true, 2)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t9', 'day1', 'Issue Jera clothing (Week 1-2)', 'joann', 'medium', null, 7, 'admin', false, 3)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t10', 'day1', 'Create Jera email address', 'siko', 'high', 'microsoft', 0, 'admin', false, 4)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t11', 'it', 'Configure laptop & install software', 'siko', 'high', 'microsoft', 1, 'admin', false, 1)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t12', 'it', 'Assign Microsoft 365 licence', 'raymond', 'high', 'microsoft', 1, 'admin', false, 2)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t13', 'it', 'Setup Outlook, Teams, SharePoint', 'raymond', 'high', 'microsoft', 1, 'admin', false, 3)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t14', 'it', 'Activate MFA on all accounts', 'siko', 'high', 'microsoft', 1, 'admin', false, 4)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t15', 'it', 'Assign Zoho One licence (Projects + Desk)', 'ryan', 'high', 'zoho', 1, 'admin', false, 5)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t16', 'it', 'Create Memtime account', 'raymond', 'medium', 'microsoft', 1, 'admin', false, 6)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t17', 'it', 'Setup VPN access', 'siko', 'medium', null, 1, 'admin', false, 7)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t18', 'it', 'Setup email signature (template from Ryan)', 'siko', 'medium', 'microsoft', 2, 'admin', false, 8)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t19', 'it', 'Setup Teams background (from Ryan)', 'siko', 'low', 'microsoft', 2, 'admin', false, 9)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t30', 'it', 'Verify: Logged into Microsoft 365 (Outlook, Teams)', null, 'high', 'microsoft', 1, 'employee', false, 10)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t31', 'it', 'Verify: OneDrive syncing & accessible', null, 'high', 'microsoft', 1, 'employee', false, 11)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t32', 'it', 'Verify: Logged into Zoho Projects', null, 'high', 'zoho', 1, 'employee', false, 12)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t33', 'it', 'Verify: Logged into Zoho Desk', null, 'high', 'zoho', 1, 'employee', false, 13)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t34', 'it', 'Verify: Memtime installed & tracking', null, 'medium', 'microsoft', 1, 'employee', false, 14)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t35', 'it', 'Verify: VPN connected successfully', null, 'medium', null, 1, 'employee', false, 15)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t20', 'hr', 'Complete tax & banking detail forms', 'hr', 'high', null, 2, 'admin', false, 1)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t21', 'hr', 'Register on payroll system', 'hr', 'high', null, 2, 'admin', false, 2)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t22', 'hr', 'Medical aid & pension registration', 'hr', 'medium', null, 3, 'admin', false, 3)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t24', 'training', '1-on-1 with manager: role & goals', 'ryan', 'high', null, 3, 'employee', false, 1)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t25', 'training', 'Complete Zoho Projects SOP walkthrough', 'ryan', 'high', 'zoho', 4, 'employee', false, 2)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t26', 'training', 'Complete Zoho Desk SOP walkthrough', 'ryan', 'high', 'zoho', 4, 'employee', false, 3)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t36', 'training', 'Complete Timekeeping SOP walkthrough', 'ryan', 'high', null, 4, 'employee', false, 4)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t37', 'training', 'Complete Client Access SOP', 'ryan', 'high', null, 4, 'employee', false, 5)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t38', 'training', 'Read & acknowledge all 20 HR policies', 'ryan', 'high', null, 5, 'employee', false, 6)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t27', 'training', 'Assign mentor for first 30 days', 'ryan', 'medium', null, 5, 'admin', false, 7)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
insert into onboarding_tasks (id, phase_id, title, default_owner, priority, system, days_offset, visibility, manager_hidden, sort_order) values ('t28', 'training', 'Schedule weekly check-ins (Month 1)', 'hr', 'medium', 'zoho', 5, 'admin', false, 8)
  on conflict (id) do update set phase_id=excluded.phase_id, title=excluded.title, default_owner=excluded.default_owner, priority=excluded.priority, system=excluded.system, days_offset=excluded.days_offset, visibility=excluded.visibility, manager_hidden=excluded.manager_hidden, sort_order=excluded.sort_order;
commit;
